[general]
import = ["themes/rose-pine.toml"]

[font]
size = 17
normal = { family = "IosevkaTerm Nerd Font", style = "Medium" }
bold = { family = "IosevkaTerm Nerd Font", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTerm Nerd Font", style = "Bold Italic" }

[window]
opacity = 1
dynamic_padding = false

[window.padding]
x = 4
y = 1

[window.dimensions]
columns = 94
lines = 33
